"""
Vérification d'intégrité des fichiers source izvox.

Le manifest `SOURCES.sha256` est généré à chaque release par
`tools/sign_sources.py`. Au démarrage en mode strict, izvox recalcule
les hashes des fichiers listés et refuse de démarrer si l'un d'eux a
été modifié.

LIMITE ASSUMÉE : sans signature externe (cosign sur le manifest, Tier 3),
un attaquant qui modifie un .py peut aussi regénérer le manifest. Le
contrôle protège contre :
- Modifications accidentelles
- Tampering en l'absence d'accès au générateur
- Détection rétroactive si on a une copie hors-bande du manifest

Pour de la vraie défense contre un attaquant motivé : signer le manifest
avec cosign et vérifier la signature au runtime (Tier 3).
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

logger = logging.getLogger(__name__)


# Extensions considérées comme "source" izvox. Évite de hasher les modèles,
# les caches Python, les venvs, etc.
SOURCE_EXTENSIONS = {".py", ".yaml", ".yml", ".toml", ".json", ".md"}
# Sous-répertoires à scanner
SOURCE_DIRS = {"src", "tests", "tools", "config", "scripts", "docs"}
# Fichiers racine spécifiquement inclus
ROOT_FILES = {
    "README.md", "LICENSE", "requirements.txt", "requirements_cuda.txt",
    "requirements_directml.txt", "requirements_cpu.txt",
    "pyproject.toml", "setup.py", ".gitignore",
}
# Patterns à exclure
EXCLUDE_PATTERNS = {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}


@dataclass(frozen=True)
class IntegrityCheckResult:
    ok: bool
    total: int
    mismatched: List[str]
    missing: List[str]
    extra: List[str]   # Hors manifest mais présents (warning seulement)


def _is_excluded(path: Path) -> bool:
    return any(part in EXCLUDE_PATTERNS for part in path.parts)


def iter_source_files(root: Path) -> Iterable[Tuple[Path, str]]:
    """Yield (absolute_path, relpath_str) pour chaque source izvox."""
    root = root.resolve()

    for fname in ROOT_FILES:
        p = root / fname
        if p.exists() and p.is_file():
            yield p, fname

    for subdir in SOURCE_DIRS:
        sub_root = root / subdir
        if not sub_root.exists():
            continue
        for p in sub_root.rglob("*"):
            if not p.is_file():
                continue
            if _is_excluded(p):
                continue
            if p.suffix.lower() not in SOURCE_EXTENSIONS:
                continue
            rel = p.relative_to(root).as_posix()
            yield p, rel


def compute_source_hashes(root: Path) -> Dict[str, str]:
    """Calcule {relpath -> sha256} pour toutes les sources izvox."""
    hashes: Dict[str, str] = {}
    for abspath, rel in iter_source_files(root):
        h = hashlib.sha256()
        with abspath.open("rb") as f:
            for chunk in iter(lambda: f.read(1 << 16), b""):
                h.update(chunk)
        hashes[rel] = h.hexdigest()
    return hashes


def load_source_manifest(manifest_path: Path) -> Dict[str, str]:
    """Lit un fichier `SOURCES.sha256` au format `<hash>  <relpath>` par ligne."""
    if not manifest_path.exists():
        return {}
    out: Dict[str, str] = {}
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(maxsplit=1)
        if len(parts) != 2:
            continue
        sha, rel = parts
        out[rel] = sha.lower()
    return out


def write_source_manifest(manifest_path: Path,
                          hashes: Dict[str, str]) -> None:
    """Écrit un manifest au format `sha256sum` standard."""
    lines = [
        "# izvox source integrity manifest",
        "# Format: <sha256>  <relpath>",
        "# Generated by tools/sign_sources.py",
        "",
    ]
    for rel in sorted(hashes):
        lines.append(f"{hashes[rel]}  {rel}")
    manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def verify_source_integrity(
    root: Path,
    manifest_path: Path,
    allow_extra: bool = True,
) -> IntegrityCheckResult:
    """Compare les hashes actuels au manifest.

    Args:
        root: racine du projet.
        manifest_path: chemin vers `SOURCES.sha256`.
        allow_extra: si False, refuse les fichiers présents mais absents
            du manifest.
    """
    expected = load_source_manifest(manifest_path)
    actual = compute_source_hashes(root)

    mismatched: List[str] = []
    missing: List[str] = []
    extra: List[str] = []

    for rel, exp_hash in expected.items():
        act_hash = actual.get(rel)
        if act_hash is None:
            missing.append(rel)
        elif act_hash.lower() != exp_hash.lower():
            mismatched.append(rel)

    for rel in actual:
        if rel not in expected:
            extra.append(rel)

    ok = not mismatched and not missing and (allow_extra or not extra)
    return IntegrityCheckResult(
        ok=ok,
        total=len(expected),
        mismatched=mismatched,
        missing=missing,
        extra=extra,
    )
